// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmoinbmrfggkfcniisva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhtb2luYm1yZmdna2Zjbmlpc3ZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNjEyMTUsImV4cCI6MjA3MTgzNzIxNX0.uTOl4Je6O3XLAiAfIWIQC5JotvxrQb96z4_W2C6ZeNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});